version: '3.7'

services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=yii2-base
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password

  app:
    image: wyveo/nginx-php-fpm:latest
    depends_on:
      - db
    working_dir: /data
    volumes:
    - ./src:/data
    - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: todo.docker.dev
